### ISSUE TITLE
Step failing in GitHub action

### ISSUE THREAD

**Issue by richard-uzik-accenture** [bluefirex/pushnotifier-send-action#1]
# Could you help me please?
GitHub action is failing even if i followed documentation.
I recieve this error : 
Run bluefirex/pushnotifier-send-action@v1.0.1
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
```
- /home/runner/work/_actions/bluefirex/pushnotifier-send-action/v1.0.1/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/bluefirex/pushnotifier-send-action/v1.0.1/dist/index.js:25:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/bluefirex/pushnotifier-send-action/v1.0.1/dist/index.js'
  ]
***
```
when using this yaml code:

```
- name: Send push notification
  id: pushnotifier
  uses: bluefirex/pushnotifier-send-action@v1.0.1
  with:
    api-token: ${{ secrets.PUSHNOTIFIER_API_TOKEN }}
    app-token: ${{ secrets.PUSHNOTIFIER_APP_TOKEN }}
    package: com.github.resume
    device-ids: ElNN
    notification: CI action for Resume application to Test completed!
    url: https://github.com/
```
